version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      mockito:
        patterns:
          - "mockito"
          - "*mockito"
          - "*mockito*"
